---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    region: us-west-1   
  tasks:  
    - name: launch instance
      ec2:
        region: "{{ region }}"  
        key_name: tgkey1  
        instance_type: g2.2xlarge  
        image: ami-b16136d1
        wait: yes    
        group: sg_jupserver_uswest
      register: ec2
    - name: associate new EIP for the instance    
      ec2_eip:
        region: "{{ region }}"
        device_id: "{{ item }}"
      with_items: "{{ ec2.instance_ids }}"
